# Site settings
name: All The Stations
email: press@allthestations.co.uk
domain: https://khawkins98.github.io/all-the-stations
baseurl: /
permalink: pretty

# Add custom CSS / JS here
custom_css:
- "/assets/app.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
# custom_js:
# - "{{site.baseurl}}/static/js/YOUR-CSS-COMPONENTS.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"

# Build settings
markdown: kramdown
