# Site settings
name: All The Stations
email: press@allthestations.co.uk
domain: http://allthestations.co.uk
baseurl: /
permalink: pretty

# Add custom CSS / JS here
custom_css:
- "/assets/app.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
# custom_js:
# - "{{site.baseurl}}/static/js/YOUR-CSS-COMPONENTS.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"

# Build settings
markdown: kramdown
timezone: Etc/GMT

gems:
  - jekyll-redirect-from
